services:
  - name: oralscan-backend
    repo: https://github.com/miteshkaliya1/OralScan
    root: backend
    buildCommand: cd .. && npm install --prefix backend && npx prisma generate --prefix backend
    startCommand: npm run start --prefix backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        value: https://oralscan-frontend.onrender.com
    plan: free